name: ‘ydp-mouse’
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano//zmk"]'
      shield: '["corne_left","corne_right"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_RGB_UNDERGLOW=y\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000\n"]'
